apply plugin: 'com.android.library'
apply from: "$project.rootProject.projectDir/linters.gradle"

android {
    namespace 'com.github.barriosnahuel.vossosunboton.model'

    compileSdkVersion "android-37.0"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 37
    }

    resourcePrefix 'model_'

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(':commons_file')

    implementation libs.timber
    implementation libs.androidx.annotation
}
