# These are supported funding model platforms; see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
ko_fi: barriosnahuel
custom:
  - https://cafecito.app/barriosnahuel
