buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url = 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath libs.build.agp
        classpath libs.build.google.services

        classpath libs.build.firebase.crashlytics.gradle
        classpath libs.build.firebase.perf.plugin

        classpath libs.build.kotlin.gradle
        classpath libs.build.kotlin.compose

        classpath libs.build.detekt.gradle
        classpath libs.build.ktlint.gradle
        classpath libs.build.spotless.gradle

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
