apply plugin: 'io.gitlab.arturbosch.detekt'
apply plugin: 'org.jlleitschuh.gradle.ktlint'
apply plugin: 'com.diffplug.spotless'

/**
 * Configuration for `io.gitlab.arturbosch.detekt` plugin
 */
detekt {
    config = files("$project.rootProject.projectDir/config/detekt/detekt-config.yml")
    buildUponDefaultConfig = true
}

/**
 * Configuration for `org.jlleitschuh.gradle.ktlint` plugin
 */
ktlint {
    android = true
    outputToConsole = true
    version = libs.versions.ktlint.get()
}

/**
 * Configuration for `com.diffplug.spotless` plugin
 */
spotless {
    kotlin {
        licenseHeaderFile(rootProject.file("config/spotless/copyright.kt"))
        target("src/**/*.kt")
    }
}

android {
    lint {
        checkDependencies = true
        lintConfig = file("$project.rootProject.projectDir/config/android/android-lint.xml")
    }
}
