apply plugin: 'io.gitlab.arturbosch.detekt'
apply plugin: 'org.jlleitschuh.gradle.ktlint'

/**
 * Configuration for `io.gitlab.arturbosch.detekt` plugin
 */
detekt {
    config = files("$project.rootProject.projectDir/config/detekt/detekt-config.yml")
    buildUponDefaultConfig = true
}

/**
 * Configuration for `org.jlleitschuh.gradle.ktlint` plugin
 */
ktlint {
    android = true
    outputToConsole = true
    version = libs.versions.ktlint.get()
}

android {
    lint {
        checkDependencies = true
        lintConfig = file("$project.rootProject.projectDir/config/android/android-lint.xml")
    }
}
