apply plugin: 'com.android.dynamic-feature'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply from: "$project.rootProject.projectDir/linters.gradle"

android {
    namespace = 'com.github.barriosnahuel.vossosunboton.feature.addbutton'

    compileSdkVersion "android-37.0"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 37
    }

    resourcePrefix = 'feature_addbutton_'

    buildTypes {
        release {
            // You must use the following property to specify additional ProGuard rules for dynamic feature modules.
            // https://developer.android.com/guide/app-bundle/at-install-delivery#dynamic_feature_proguard
            proguardFiles 'proguard-rules-dynamic-features.pro'
        }
    }
    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation project(':app')
    implementation project(':commons_android')
    implementation project(':commons_file')
    implementation project(':model')

    implementation libs.coroutines.core
    implementation libs.coroutines.android

    implementation libs.timber
    implementation libs.androidx.annotation

    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.compose.material.icons.extended
    implementation libs.androidx.activity.compose
    implementation libs.lifecycle.viewmodel.compose
    implementation libs.lifecycle.runtime.compose

    debugImplementation libs.compose.ui.tooling
}
