complexity:
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 7
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']
  CyclomaticComplexMethod:
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    thresholdInClasses: 15
    ignoreOverridden: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 150
  MagicNumber:
    ignorePropertyDeclaration: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
