complexity:
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 7
    ignoreDefaultParameters: true
  TooManyFunctions:
    thresholdInClasses: 12

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 150
  MagicNumber:
    ignorePropertyDeclaration: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
